
<<<<<<< HEAD
rest-api:
=======
restapi:
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
  name: rest-api-deployment
  labels:
      app: rest-api
  serviceName: rest-api-service
  replicas: 3
  template:
    spec:
      containers:
<<<<<<< HEAD
        - name: rest-api-container
          image: eu.gcr.io/earnest-acre-297416/rest-api
          ports:
            - containerPort: 5000
=======
          name: rest-api-container
          image: eu.gcr.io/earnest-acre-297416/rest-api
          ports:
              containerPort: 5000
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
              port: 5000
              servicePort: 5000

frontend:
  metadata:
    name: test-deployment
    labels:
      app: test
    serviceName: rest-api-service
  replicas: 3
<<<<<<< HEAD
    selector:
      spec:
        containers:
        - name: itest-container
          image: eu.gcr.io/earnest-acre-297416/ui-test
          ports:
          - containerPort: 80
=======
  containers:
          name: itest-container
          image: eu.gcr.io/earnest-acre-297416/ui-test
          ports:
            containerPort: 80
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
            nodePort: 30002
            port: 8091
            targetPort: 80

postgres:
  apiVersion: v1
  image: postgres:13.1-alpine
  replicas: 1
  kind: ConfigMap
  ports:
<<<<<<< HEAD
    - port: 5432
=======
      port: 5432
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
      nodePort: 30001
      targetPort: 5432
  metadata:
    name: postgres-config
    labels:
      app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: postgresadmin
    POSTGRES_PASSWORD: admin123
    POSTGRES_PORT: "5432"
    DATABASE_URL: postgres://postgresadmin:admin123@postgres-service:5432/postgresdb

  PersistentVolume:
    hostPath:
      path: "/var/lib/data"
    capacity:
      storage: 5Gi
    accessModes:
<<<<<<< HEAD
      - ReadWriteMany
  PersistentVolumeClaim:
    accessModes:
      - ReadWriteMany
=======
       ReadWriteMany
  PersistentVolumeClaim:
    accessModes:
       ReadWriteMany
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
    capacity:
      storage: 5Gi
