
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.frontend.metadata.name}}
  labels:
    app: {{.Values.frontend.metadata.labels.app}}
spec:
  replicas: {{.Values.frontend.metadata.replicas}}
  selector:
    matchLabels:
      app: {{.Values.frontend.metadata.labels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.frontend.metadata.labels.app}}
    spec:
      containers:
      - name: {{.Values.frontend.spec.spec.containers.name}}
        image: {{.Values.frontend.spec.spec.containers.image}}
        ports:
        - containerPort: {{.Values.frontend.spec.spec.containers.ports.containerPort}}