apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend.metadata.serviceName}}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: {{.Values.frontend.containers.ports.nodePort}}
    port: {{.Values.frontend.containers.ports.port}}
    targetPort: {{.Values.frontend.containers.ports.targetPort}}
  selector:
    app: {{.Values.frontend.metadata.labels.app}}
