apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend.metadata.serviceName}}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30002
  - port: 8091
    targetPort: 80
  selector:
    app: {{.Values.frontend.metadata.labels.app}}
