kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: {{.Values.postgres.metadata.labels.app}}
spec:
  storageClassName: slow
  capacity:
    storage: {{.Values.postgres.PersistentVolume.capacity.storage}}
  accessModes:
    - {{.Values.postgres.PersistentVolume.accessModes}}
  hostPath:
    path: {{.Values.postgres.PersistentVolume.hostPath.path}}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: {{.Values.postgres.metadata.labels.app}}
spec:
  storageClassName: slow
  accessModes:
    - {{.Values.postgres.PersistentVolumeClaim.accessModes}}
  resources:
    requests:
      storage: {{.Values.postgres.PersistentVolumeClaim.capacity.storage}}
