kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
<<<<<<< HEAD
    app: postgres
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/data"
=======
    app: {{.Values.postgres.metadata.labels.app}}
spec:
  storageClassName: slow
  capacity:
    storage: {{.Values.postgres.PersistentVolume.capacity.storage}}
  accessModes:
    - {{.Values.postgres.PersistentVolume.accessModes}}
  hostPath:
    path: {{.Values.postgres.PersistentVolume.hostPath.path}}
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
<<<<<<< HEAD
    app: postgres
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
=======
    app: {{.Values.postgres.metadata.labels.app}}
spec:
  storageClassName: slow
  accessModes:
    - {{.Values.postgres.PersistentVolumeClaim.accessModes}}
  resources:
    requests:
      storage: {{.Values.postgres.PersistentVolumeClaim.capacity.storage}}
>>>>>>> b75e83abf86f899e2739f0f2b56133a8c58813cb
