apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: {{.Values.ports.port}}
      nodePort: {{.Values.ports.nodePort}}
      targetPort: {{.Values.ports.targetPort}}
  selector:
    app: {{.Values.postgres.metadata.labels.app}}