
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{.Values.postgres.data.POSTGRES_DB}}
  POSTGRES_USER: {{.Values.postgres.data.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{.Values.postgres.data.POSTGRES_PASSWORD}}
  POSTGRES_PORT: {{.Values.postgres.data.POSTGRES_PORT}}
  DATABASE_URL: {{.Values.postgres.data.DATABASE_URL}}
