apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: {{.Values.restapi.name}}
spec:
  replicas: {{.Values.restapi.replicas}}
  selector:
    matchLabels:
      app: {{.Values.restapi.labels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.restapi.labels.app}}
    spec:
      containers:
        - name: {{.Values.restapi.template.spec.containers.name}}
          image: {{.Values.restapi.template.spec.containers.image}}
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom: 
                configMapKeyRef:
                  name: postgres-config
                  key: DATABASE_URL
            - name: FLASK_ENV
              value: development
