apiVersion: v1
kind: Service
metadata:
  name: {{.Values.restapi.serviceName}}
spec:
  type: ClusterIP
  ports:
      protocol: TCP
    - port: 5000
      targetPort: 5000
  selector:
    app: {{.Values.restapi.labels.app}}
