
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.rest-api.serviceName}}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{.Values.rest-api.template.spec.containers.ports.servicePort}}
      targetPort: {{.Values.rest-api.template.spec.containers.ports.port}}
  selector:
    app: {{.Values.rest-api.labels.app}}